import { DM_Sans } from "next/font/google";
import "./globals.css";

import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
const inter = DM_Sans({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
      {children}
      <iframe className="bottom-0 right-0 fixed m-8 opacity-90 rounded-md backdrop-blur-md shadow-xl" width={320} height={560}  src="https://nutrisnap-chat.vercel.app/"></iframe>
      <Footer />
</body>
    </html>
  );
}
